<a href="https://colab.research.google.com/github/joyjelly/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [ ]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)
## CSV 형식 저장
df.to_csv('student_analysis.csv',encoding='utf-8',index =False)

## 5-2 JSON 형식 저장

In [5]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장  -->indent = 4 가 뭔뜻?
with open('output.json',mode='w',encoding='utf-8') as f:
    json.dump(data , f, indent = 4 ,ensure_ascii=False)
## DataFrame을 이용한 저장 -->orient 가 뭔뜻?
df = pd.DataFrame(data)
df.to_json('output_json.json', orient='records',indent =4 ,force_ascii = False)

df = pd.DataFrame([data])

## 5-3 Pandas Dataframe 데이터 추출

In [7]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
# () 안에 data와 [] data의 차이
df
## DataFrame 인덱스 출력
print(df.index)
## DataFrame 컬럼 출력
print(df.columns)
## DataFrame 행 출력 -> 두개 차이??
print(df.values.tolist())
print(df.values)

## DataFrame 값 출력
print(df.values.flatten())

    이름  학년   학점     학과    동아리
0  김철수   1  4.2   컴퓨터학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5     농학   로봇공학
3  최지훈   4  3.9    교육학   봉사활동
4  정소희   2  3.5  영어영문학   음악감상

## 5-4 DataFrame 생성 방법

In [8]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1=pd.DataFrame.from_dict(data)
df2=pd.read_csv('students.csv')
df3=pd.read_json('students.json')
## 세가지 방법 결과 비교

print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [9]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df= pd.DataFrame(data)
## CSV, JSON 형식으로 저장
df.to_csv('students_score.csv')
df.to_json('students_score.json')
## HTML 형식으로 저장
html_table = df.to_html()
print(html_table)
with open('students_score.html',mode='w',encoding='utf-8') as f:
    f.write(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터공학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>전자공학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>의학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>심리학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

## 5-6 실습 시나리오

## 데이터 수집

In [13]:
import requests

url = "https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getMinuDustFrcstDspth"
api_key = ''

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'response': {'body': {'totalCount': 832, 'items': [{'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'PM25', 'dataTime': '2026-10-09'}, {'informCode': 'O3', 'dataTime': '2026-10-09'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'PM25', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-08'}, {'informCode': 'PM10', 'dataTime': '2026-10-08'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'PM25', 'dataTime': '2026-10-07'}, {'informCode': 'O3', 'dataTime': '2026-10-07'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'PM25', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'O3', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}, {'informCode': 'PM10', 'dataTime': '2026-10-06'}], 'pageNo': 1, 'numOfRows': 100}, 'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

## 데이터 프레임 생성

In [21]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기 ->to_json() 밑 []이 대괄호들의 의미가뭘까
data = response.json()['response']['body']['items']
print(type(data))
print(len(data))
print(data[0])
df=pd.DataFrame(data)
df

<class 'list'>
100
{'informCode': 'O3', 'dataTime': '2026-10-09'}

   informCode    dataTime
0          O3  2026-10-09
1        PM25  2026-10-09
2        PM10  2026-10-09
3        PM10  2026-10-09
4        PM25  2026-10-09
..        ...         ...
95       PM25  2026-10-06
96         O3  2026-10-06
97         O3  2026-10-06
98       PM10  2026-10-06
99       PM10  2026-10-06

[100 rows x 2 columns]

## 다양항 형식으로 데이터 저장

In [22]:
# CSV 형식 데이터 저장
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json',indent=4,force_ascii=False)
## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx',index=False)
## HTML 형식 데이터 저장
df.to_html('air_pollution.html')